name: Android CI
#https://medium.com/@wkrzywiec/github-actions-for-android-first-approach-f616c24aa0f9

on:
  push:
    branches:
      - '*'
      - '!master'
      - '!release*'
  pull_request_review:
    types: [edited, submitted]

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Unit Tests
        run: ./gradlew detekt testDebugUnitTest runTestsInCI '-PCI=true'
